# Generated by Django 3.2.25 on 2025-04-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_rename_student_login_informatn_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_ID',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
