# Generated by Django 3.2.25 on 2025-04-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_auto_20250411_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seats_total',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
