# Generated by Django 3.2.25 on 2025-04-22 21:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_auto_20250412_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment_comments',
            options={'verbose_name': 'Assignemt Comment', 'verbose_name_plural': 'Assignment comments'},
        ),
        migrations.AlterModelOptions(
            name='grade_student',
            options={'verbose_name': 'Grade student', 'verbose_name_plural': 'Grade students'},
        ),
        migrations.AlterModelOptions(
            name='store_email_stu_new',
            options={'verbose_name': 'Student Email', 'verbose_name_plural': 'All Student Emails'},
        ),
        migrations.AlterModelOptions(
            name='store_email_teach_new',
            options={'verbose_name': 'Teacher Email', 'verbose_name_plural': 'All Teacher Emails'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student Information', 'verbose_name_plural': 'Students Information'},
        ),
        migrations.AlterModelOptions(
            name='student_courses_with_teacher_name',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'All Courses'},
        ),
        migrations.AlterModelOptions(
            name='student_submit_assignment_pro',
            options={'verbose_name': 'Student Assignment', 'verbose_name_plural': 'Student Assignments'},
        ),
        migrations.AlterModelOptions(
            name='teacher_assignment_upload_file',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='teacher_login_informa',
            options={'verbose_name': 'Teacher Information', 'verbose_name_plural': 'Teachers Information'},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='date_enrolled',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schoolapp.student_courses_with_teacher_name'),
        ),
    ]
