# Generated by Django 3.2.25 on 2025-04-23 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_auto_20250422_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_submit_assignment_pro',
            name='Submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
