# Generated by Django 3.2.25 on 2025-04-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_auto_20250426_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='student_profiles/default_stu.png', upload_to='student_profiles/'),
        ),
        migrations.AddField(
            model_name='teacher_login_informa',
            name='profile_pic',
            field=models.ImageField(default='teacher_profiles/default_tea.png', upload_to='teacher_profiles/'),
        ),
    ]
